# 3.18 is needed for openssl1.1-compat
FROM node:18-alpine AS base

WORKDIR /app
ENV NODE_OPTIONS=--openssl-legacy-provider
# RUN apk add --no-cache openssl1.1-compat # needed for prisma to work

FROM base AS frontend

COPY client/package.json client/package-lock.json ./

RUN npm install --ignore-scripts

COPY client/ .

ARG REACT_APP_API_ENDPOINT=https://damm.datasektionen.se
ARG REACT_APP_S3_BUCKET=dsekt-damm-prod

RUN npm run build --ignore-scripts

FROM base AS backend

COPY package.json package-lock.json ./

RUN npm install --ignore-scripts

COPY prisma/ prisma/

RUN npx prisma generate

COPY common/ common/
COPY functions/ functions/
COPY routes/ routes/
COPY app.ts fuzzyfile.json tsconfig.json ./

RUN npm run build

FROM base

RUN apk add nginx

COPY --from=backend /app/prisma /app/prisma
COPY --from=backend /app/node_modules /app/node_modules
COPY --from=backend /app/dist /app/dist
COPY --from=frontend /app/build/ /app/dist/client/build/

RUN echo "nginx -g 'daemon off;' &" >> run.sh
RUN echo "npx prisma migrate deploy && node dist/app.js" >> run.sh
# RUN echo "wget http://nyckeln:7004/api/v1/user/turetek/permissions" >> run.sh
# RUN echo "wget http://localhost:7003/api/users?format=single&u=turetek" >> run.sh
# RUN echo "wget http://localhost:7002/hello" >> run.sh
# RUN echo "nginx -T" >> run.sh
RUN chmod +x run.sh

ENTRYPOINT ./run.sh
